[versions]
agp = "9.0.0"
appCompatVersion = "1.3.1"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
coroutinesTest = "1.10.2"
mockk = "1.14.9"
robolectric = "4.16.1"
lifecycleRuntimeKtx = "2.6.1"
androidMaterial = "1.11.0"
gsonVersion = '2.9.0'
koinVersion = "3.5.6"
navigation = "2.9.7"
ktxfragment = "1.7.1"
currencyVersion= "2.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompatVersion" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation"  }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "ktxfragment" }
gson = { group  = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }
koin = { group  = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }
koin-core = { group  = "io.insert-koin", name = "koin-core", version.ref = "koinVersion" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koinVersion" }
koin-junit-test = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koinVersion" }
currency-formatter = { group = "com.github.BlacKCaT27", name="CurrencyEditText", version.ref = "currencyVersion" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

[plugins]
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
android-application = { id = "com.android.application", version.ref = "agp" }